### ISSUE TITLE
Background Color and Logo do not match

### ISSUE THREAD

**Issue by bloodmandarin** [Mindful-Meerkats/mindful-meerkats-org#11]
The colors are different. 
Unfortunately it appears like Telmo has used three different colors in his delivered files:
 #FBBA03
# fdc325
# fdc415

**Comment by bloodmandarin** [comment]
Tried to adapt color in Wordpress (Yay, I found where to look! ;) ), but did not find the right one. And I did manage to install Gcolor on a Linux computer. ;)

**Comment by orschiro** [comment]
Fixed using `#FDC415`. 

> And I did manage to install Gcolor on a Linux computer. ;)

I'm so unbelievably proud of you! :)

**Comment by orschiro** [comment]
@bloodmandarin 

Why did you reopen the issue?

**Comment by bloodmandarin** [comment]
Because it is still wrong and I wanted to add a screenshot, but the page is down again...

**Comment by orschiro** [comment]
Not applicable on my system. 

![screenshot-www mindful-meerkats org 2015-11-08 10-16-19](https://cloud.githubusercontent.com/assets/170947/11019665/24ad6918-8603-11e5-9240-5bb2264db826.png)
